export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: '0.4rem',
  },
  media: {
    isDesktopOrLaptop: '(min-device-width: 1024px)',
    isBigScreen: '(min-device-width: 1824px)',
    isTabletOrMobile: '(max-width: 1024px)',
    isTabletOrMobileDevice: '(max-device-width: 1024px)',
    isMobileDevice: '(max-width: 500px)',
    isTinyDevice: '(max-width: 370px)',
    isPortrait: '(orientation: portrait)',
    isRetina: '(min-resolution: 2dppx)',
  },
  font: {
    fontStackBase:
      '-apple-system, BlinkMacSystemFont, "San Francisco", "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    fontStackMonospace: 'Monaco, Consolas, "Lucida Console", monospace',
    family:
      "-apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, Helvetica Neue, sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
  },
  colors: {
    primary: '#003cde',
    interactive: '#001837',

    grayBackground: '#f9f9f9',
    grayLight: '#efefef',
    grayLighter: '#f3f4f4',
    gray: '#dee1e5',
    grayDark: '#7a838e',
    blueGrayLight: '#98a8bc',
    blueGray: '#5b6b7f',
    blackBlue: '#001837',
    blueLightest: '#edf2ff',
    blueLighter: '#6891ff',
    blueLight: '#3e72ff',
    blue: '#003cde',
    blueDark: '#001a60',
    blueDarker: '#00103c',
    green: '#50b83c',
    yellow: '#ffae02',
    red: '#f75c43',
    blueHover: '#f3f6fe',
    badgeBlue: '#b4c6f9',
    badgeGreen: '#b7e2af',
    badgeOrange: '#f9bc85',
    badgeYellow: '#fbd687',
    bannerDefaultBackground: '#F4F6F8',
    bannerDefaultBorder: '#98a8bc',
    bannerErrorBackground: '#FCF0EC',
    bannerInfoBackground: '#F1F7FB',
    bannerSuccessBackground: '#ebfbe8',
    bannerWarningBackground: '#FDF7E5',
    dvGreen: '#b7dfcb',
    dvLightBlue: '#5abad1',
    dvMidBlue: '#3984b5',
    dvDarkBlue: '#264992',
    dvBlackBlue: '#161f63',
    invGold: '#8c7041',
    invBlack: '#2b3c4c',
    darkGray: '#7a838e',
    lightGreen: '#b7e2af',
    // unknown colors
    white: '#ffffff',
    darkest: '#212B36',
    transparentBackground: 'rgba(99, 114, 130, 0.5)',
    selago: '#f3f6fe',
    orange: '#fbd687',
    zircon: '#edf2ff',
    lightRed: '#f9bc85',
    offYellow: '#fef8e6',
    cornHarvest: '#956e07',
    galliano: '#e19f05',
    matisse: '#1f5fa1',
    greenForest: '#008b4a',
    orangeBrown: '#8a6116',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
};
